import React from "react";
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import HomePage from './Home';


export default function Home() {
    return (
        <>
            <Head>
                {/*<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"/>*/}
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={""} >

                    <HomePage/>

                    {/*<Ogoxe/>*/}

                    {/*<Extra/>*/}
            </main>

        </>
    )
}