import React from "react";
import Head from 'next/head'
import HomePage from './Home';
import TopPage from "@/components/TopPage";
import BotPage from "@/components/BotPage";


export default function Home() {
    return (
        <>
            <Head>
                {/*<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"/>*/}
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>


            </Head>

            <div className="min-h-screen flex flex-col justify-between dark:bg-zinc-900">
                <TopPage/>
                <HomePage/>
                <BotPage/>
            </div>

        </>
    );
}