import React from "react";
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Ogoxe from './Ogoxe';
import Extra from './Extra';
import HomePage from './Home';

//Branche V0

export default function Home() {
    return (
        <>
            <Head>
                {/* eslint-disable-next-line @next/next/google-font-display,@next/next/no-page-custom-font */}
                <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet"/>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={"bg-gray-200 px-10"} >

                <section className={"min-h-screen"}>

                    <HomePage/>

                    <Ogoxe/>

                    <Extra/>

                </section>

            </main>
        </>
    )
}